# Generated by Django 4.1.7 on 2023-02-20 05:03

from django.db import migrations, models
import quiz_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizinfo',
            name='data',
            field=models.JSONField(default=quiz_app.models.set_default_quiz_data),
        ),
    ]
