# Generated by Django 4.1.7 on 2023-03-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_userquizinfo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationinfo',
            name='pay_status',
            field=models.CharField(choices=[('free', 'free'), ('paid', 'paid')], default='free', max_length=7),
        ),
    ]
